name = "MyPkg"
uuid = "7f3923a3-495a-4db3-b9f3-c24cf85e0e2f"
authors = ["maysam-gholampour <meysam.gholampoor@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1.11"

[extras]
JET = "c3a54625-cd67-489e-a8e7-0a5a0ff4e31b"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["JET", "Test"]
